modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/ExpensiveKoala/Clear-Water/issues"
[[mods]]
modId = "clearwater"
version = "${version}"
displayName = "Clear Water"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/clear-water"
logoFile = "icon.png"
authors = "ExpensiveKoala, AlexNijjar"

description = '''
See clearly under water!
'''

[[dependencies.clearwater]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clearwater]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[2.4.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clearwater]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
